services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: ["./entrypoint.sh",]
    volumes:
      - ./backend/media:/app/media
    ports:
      - "127.0.0.1:8010:8000"  # Bind to localhost only
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"  # Bind to localhost if you need host access; otherwise remove

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production} # Default to prod
    volumes:
      - /app/node_modules # Keep this to isolate deps
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production} # Default to prod
    depends_on:
      - backend

volumes:
  postgres_data: