services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: ["./entrypoint.sh",]
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "127.0.0.1:8010:8000"  # Bind to localhost only
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"  # Bind to localhost if you need host access; otherwise remove

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Pass arg: Prod builds with NODE_ENV=production
      args:
        - NODE_ENV=${NODE_ENV:-development}
    volumes:
      # Dev-only: Hot-reload source (skipped in prod via override)
      - ./frontend:/app
      - /app/node_modules  # Always: Isolate deps
    ports:
      - "127.0.0.1:3001:3000"  # Bind to localhost only
    environment:
      NODE_ENV: ${NODE_ENV:-development}  # Default dev; set to 'production' via .env or deploy
    depends_on:
      - backend

volumes:
  postgres_data:
