name: Deploy aial on master branch

on:
  push:
    branches:
      - master

jobs:
  pull_master_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Pull master branch on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/apps/aial

            git fetch origin
            git checkout master || exit 1
            git pull origin master || exit 1

#  configure_env:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    needs: pull_master_branch
#    steps:
#      - name: Ensure correct Node.js version
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          port: ${{ secrets.PORT }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd /home/ubuntu/apps/aial/frontend
#            source ~/.nvm/nvm.sh
#            nvm install 20.9.0 || exit 1

  update_master_app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # change to configure_env if it will be added
    needs: pull_master_branch
    steps:
      - name: Run Docker Compose
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker compose up -d --build

#      - name: Update and restart aial app
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          port: ${{ secrets.PORT }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd /home/ubuntu/apps/aial
#
#            sudo supervisorctl stop aial || true
#            docker compose down
#            docker compose up -d --build
#
#            sudo supervisorctl start aial || exit 1
#            sudo supervisorctl start aial-celery || true
#            sudo supervisorctl start aial-celery-beat || true

#  check_if_site_is_running:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    needs: update_master_app
#    steps:
#      - name: Check if aial site is online
#        run: curl -f -LI "http://51.83.132.17/" || exit 1
