name: Deploy aial on master branch

on:
  push:
    branches:
      - master

jobs:
  pull_master_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Pull master branch on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/apps/aial

            git fetch origin
            git checkout master || exit 1
            git pull origin master || exit 1

#  configure_env:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    needs: pull_master_branch
#    steps:
#      - name: Ensure correct Node.js version
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          port: ${{ secrets.PORT }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd /home/ubuntu/apps/aial/frontend
#            source ~/.nvm/nvm.sh
#            nvm install 20.9.0 || exit 1

  update_master_app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # change to configure_env if it will be added
    needs: pull_master_branch
    steps:
      - name: Update and restart aial app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/apps/aial
            docker compose -f docker-compose.yml -f docker-compose.prod.yml down
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
# Health: Wait & test frontend
            sleep 15
            if ! curl -f http://localhost:3001/; then
              echo "Frontend health check failed!"
              docker logs aial-frontend-1
              exit 1
            fi
            echo "Deploy successful: Frontend at http://localhost:3001"

      - name: Verify frontend logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker logs aial-frontend-1 --tail 20 || exit 1
